name: bacteria-RNAseq-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.13.15
  - cutadapt=5.2
  - minimap2=2.30
  - samtools=1.24
  - subread=2.1.1 # provides featureCounts
  - pysam
  - matplotlib
